apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: frontend
    spec:
      serviceAccountName: sql-proxy-sa
      containers:
      - name: frontend
        image: python-guestbook-frontend-django
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: database
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_HOST
          value: "127.0.0.1"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.0
        env:
        - name: CONNECTION
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: connection
        args:
          - "--health-check"
          - "--http-address=0.0.0.0"
          - "--private-ip"
          - "--structured-logs"
          - "--port=5432"
          - "$(CONNECTION)"
        securityContext:
          runAsNonRoot: true
        startupProbe:
          httpGet:
              path: /startup
              port: 9090
          periodSeconds: 1
          timeoutSeconds: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
              path: /liveness
              port: 9090
          initialDelaySeconds: 0
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 5