apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: python-guestbook
        tier: frontend
    spec:
      serviceAccountName: sql-proxy-sa
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6.0
        env:
        - name: CONNECTION
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: connection
        args:
          - "--private-ip"
          - "--structured-logs"
          - "--port=5432"
          - "$(CONNECTION)"
        securityContext:
          runAsNonRoot: true
      - name: frontend
        image: python-guestbook-frontend-django
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: guestbook-db-creds
              key: database
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_HOST
          value: "127.0.0.1"
